---
version: 2

updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - ".github/actions/setup-just"
      - ".github/actions/setup-tox"
    schedule:
      interval: "weekly"

  - package-ecosystem: "uv"
    directories:
      - ".github/actions/setup-just"
    schedule:
      interval: "weekly"
